### ISSUE TITLE
Wishlist:  the readme, (or other useful documentation like that), in a downloadable, viewable format instead of just MD

### ISSUE THREAD

**Issue by jharris1993** [till213/SkyDolly#114]
**Is your feature request related to a problem? Please describe.**
The existing documentation is a markdown file in GitHub markdown format and is not easily readable offline.

**Describe the solution you'd like**
After downloading an app, like SkyDolly, I like to download available documentation to the download folder containing the utility itself.  Unfortunately, the GitHub formatted MD file is difficult to render since it doesn't contain any of the normal "markdown" type identifiers.

Ideally, a PDF file containing the formatted text and illustrations would be invaluable.

**Describe alternatives you've considered**
I have tried Firefox's MD extension, as well as several online Markdown to PDF converters, and they don't work well with GitHub formatted files.

**Additional context**
This is the readme downloaded in RAW format from this site which I would like to be able to view without being in GitHub.

[README.md](https://github.com/till213/SkyDolly/files/12038758/README.md)

**Comment by till213** [comment]
Hello,

Thank you very much for your detailed request, very much appreciated!

It is no secret that documentation for Sky Dolly is somewhat lacking ;) While - professionally - I actually like writing (code) documentation that fell a bit short until now with Sky Dolly. A „one man project“ really.

And yes, that specifically includes the „online documentation“ (accessible from the Sky Dolly app, via your default browser) that is particularly in an extremely unfinished state (one could call it a „placeholder“).

That all being said, I might think about distributing a simple README as either plain text file, or perhaps RTF.

I don‘t intend to checkin redundant PDFs, compiled from existing MD documents.

However the given MD that you pointed out doesn‘t contain specific github markdown syntax (I am aware that such exists): it does however contain links to (telative) resources such as images - perhaps your readers stumbled over those missing resources?

I locally edit my markdowns with Visual Studio Code that provides several excellent markdown preview plugins. They work great for me.

Once I get to it I may try to „print to PDF“ for you and attach the PDF to this issue.

**Comment by till213** [comment]
As mentioned above Visual Studio Code renders the markdown just fine:

![VS Code Markdown Preview](https://github.com/till213/SkyDolly/assets/1205514/0ae57899-24b2-40d3-8bba-47efd51fd444)

I installed a "Print" extension and was able to "Print to PDF" (that is built in into macOS: I am pretty sure under Windows there exist similar "print to PDF" options), see attached PDF.

[README.md.pdf](https://github.com/till213/SkyDolly/files/12061017/README.md.pdf)

**Comment by jharris1993** [comment]
This is excellent!

A suggestion if I may.

Have you checked this in to your repo?

If not, would you please do so for the benefit of other users?  If necessary, you can indicate that this PDF is a convenience and is not guaranteed to be the most recent version.  That is, unless now that you have it, you make "create the PDF" a part of the build process.
😉

Thanks again!  This will be a huge help.

P.S.
GitHub's version of markdown doesn't include a lot of expected metadata, instead just using the markdown as if it were a rich-text document.  Because of this, 3rd party markdown converters choke on it.

I have Visual Studio Code installed on my dev computer, (which is offline right now) and I don't want to burden my flight sim system with software that isn't directly associated with flying the sim 😉 as I am sure you understand.  Thanks again for your help!

Jul 15, 2023 11:58:05 AM Oliver Knoll ***@***.***>:
