### ISSUE TITLE
The Log doesn't seem to consistently record the departure and arrival airports. For most flights it says "CustD" & "CustA".

### ISSUE THREAD

**Issue by chfisa** [till213/SkyDolly#116]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Application version:**
 - Visible in the "Info / About" dialog
 - Version [e.g. 0.5.0]

**Additional context**

**Comment by till213** [comment]
Hello,

Thank you for bringing up this issue.

Sky Dolly records the departure and arrival airport as reported by MSFS via SimConnect. This implies that you need to have an active flight plan loaded prior to starting and recording the flight, as typically done on the „world view menu“. I don‘t know if this works at all when you enter / load a flightplan when the flight has already started.

When you don‘t have a flightplan active then MSFS simply reports „custom departure/arrival“ waypoints, or in other words: Sky Dolly does not try on its own - given the GPS coordinates and some (possible) database with airport information - to determine the actual waypoints (airports). Possible, but not implemented (and not really on my mind just yet ;)).

I hope my answer clarifies this issue a bit.

Happy flying!

**Comment by chfisa** [comment]
Hi again,
Just a follow-up.
It worked perfectly, just as you suggested.
Thank you!
Richard
P.S.
BTW, I have tried the other recorders and I truly think yours is the best!
Really appreciate your efforts on this!

**Comment by till213** [comment]
Thank you for your feedback, very much appreciated. And thanks for the flowers, too ;)
