### ISSUE TITLE
script "flight analysis.sql" selecting db attribute "flight_number" not working.

### ISSUE THREAD

**Issue by jaber70599** [till213/SkyDolly#150]
**Describe the bug**
sql statement "flight analysis.sql" could not be executed.

**To Reproduce**
open sqlite db bowser. 
open script "flight analysis.sql". 
execute sql statement denoted as "Select specific values from tables position, aircraft and flight".  

**Expected behavior**
no sql error

**Screenshots**

**Context**
See #104

**Comment by till213** [comment]
The flight_number attribute has been moved from table AIRCRAFT to table FLUGHT in Sky Dolly version v0.17.

Reasoning: the flight number is specific to a „flight“ - not an individual aircraft.

That is, all aircraft in a formation flight have the same „flight number“.

-> Adjust your query accordingly.

E.g.

select flight_number from flight:;

Does that answer the wuestion?

**Comment by till213** [comment]
Btw did you forget to attach the script in question? I do not see such an attachement „flight_analysis.sql“.

**Comment by jaber70599** [comment]
> The flight_number attribute has been moved from table AIRCRAFT to table FLUGHT in Sky Dolly version v0.17.
> 
> Reasoning: the flight number is specific to a „flight“ - not an individual aircraft.
> 
> That is, all aircraft in a formation flight have the same „flight number“.
> 
> -> Adjust your query accordingly.
> 
> E.g.
> 
> select flight_number from flight:;
> 
> Does that answer the question?

yes it does.

**Comment by jaber70599** [comment]
> Btw did you forget to attach the script in question? I do not see such an attachement „flight_analysis.sql“.

sorry, for missing information. 
I am referencing to a select statement which is part of "SkyDolly/doc/SQL/Flight-Analysis.sql". Select statement goes from line 19 to line 43.

**Comment by till213** [comment]
> I am referencing to a select statement which is part of "SkyDolly/doc/SQL/Flight-Analysis.sql"

Ah… good catch! I knew the script name sounded familiar ;)

This is a documentation bug then and will be fixed asap!

Thanks for reporting!

**Comment by till213** [comment]
The example SQL script has been fixed.
