### ISSUE TITLE
Automate the Recording and Stop (duplicates #156)

### ISSUE THREAD

**Issue by jrahma** [till213/SkyDolly#157]
Please add an option to automate the start of the recording because many times players forget to record before landing. For example:

Start Recording when I am (xxx) miles from landing

Or

Start Record When I am (x) minutes before the destination

Thanks,
Jassim

**Comment by till213** [comment]
Thank you for raising this issue. I will merge it with the existing issue #156.

Your requirements „x miles | minutes before landing“ are very interesting: I‘ll see whether this information is available via the SimConnect API.
