### ISSUE TITLE
GPX file format import

### ISSUE THREAD

**Issue by scls19fr** [till213/SkyDolly#16]
Hello,

GPX is a quite used file format for GPS track.
Not as used as IGC #15 for gliders but widely used also (SDVFR for example doesn't provide IGC export but KML and GPX export).

Maybe SkyDolly could support GPX as import also
https://en.wikipedia.org/wiki/GPS_Exchange_Format

A sample file can be found at https://gist.github.com/scls19fr/36ad147517dfdf1b2d7e1ef34ecc4670

Kind regards

**Comment by till213** [comment]
Ha, that's really funny: just _hours_ ago I had a look at the GPX documenation here:

https://www.topografix.com/gpx.asp

I do have a small list of import/export formats on my own TODO list, GPX is one of them.

**Comment by till213** [comment]
Just as a heads-up:

![grafik](https://user-images.githubusercontent.com/1205514/155475765-6e6ac856-7e98-456b-a6cf-79d461aefa25.png)

Note that altitude (elevation) and timestamps are optional values in GPX, so the current solution allows to define default values in case either altitude or timestamps are missing.

Te timestamps are calculated based on the desired flight speed - which is then of course constant across the whole path. Ignoring the "extra path length" introduced later on by cubic spline interpolation - the distance is purely calculated based on the linear connection of the track points (the [Haversine ](https://www.analyzemath.com/Geometry_calculators/distance-between-two-points-on-earth.html)distance, to be specific - so not quite "linear" ;)).
