### ISSUE TITLE
Crash when trying to import KML

### ISSUE THREAD

**Issue by EagleAviator** [till213/SkyDolly#180]
**Describe the bug**
Crash while trying to import a KML generated by Foreflight
**To Reproduce**
Import KML

**Expected behavior**
KML is able to open

It wont let me upload the KML reach out and I can send it over email

**Comment by till213** [comment]
Thanks for reporting this issue.

I think you should be able to compress the KML file into a ZIP file and attach this ZIP archive to this issue.

Let me know if this still does not work.

**Comment by till213** [comment]
Note to myself: quite likely the same issue as

https://github.com/till213/SkyDolly/issues/179
