### ISSUE TITLE
Logbook File Location

### ISSUE THREAD

**Issue by seattlerust** [till213/SkyDolly#23]
The Logbook default location is in  C:\Users\Username\Documents\Sky Dolly. I have not discovered any way to change this to a different partition or folder of my own choosing. Am I missing something? If not, can this ability be added to the program?

Thank you,
Seatlerust

**Comment by seattlerust** [comment]
till213   Please explain method.

**Comment by till213** [comment]
> till213 Please explain method.

Whoooo, hold your horses there a little bit ;) You just asked this question literally 35 minutes ago ;) I was just about to answer, so give me another 5 minutes, okay? ;)

**Comment by till213** [comment]
Hello there,

There are two methods:

- You can simply create a new logbook by choosing _FIle / New Logbook..._ (or press CTLR + N)
- In the file selection dialog select any location of your liking

In case you have already made some flight recordings and you wish to keep the old logbook, but simply have it in another location, then

- Simply move the logbook from C:\Users\Your User\Documents\Sky Dolly\Sky Dolly.sdlog to the preferred location (with the File Explorer)
- Then in Sky Dolly select _File / Open Logbook..._ (or press CTRL + O) and select the moved Sky Dolly.sdlog

In both cases the newly created or just opened logbook will be the "default logbook" and whenever you restart Sky Dolly this logbook will be opened.

You can also verify this by opening the logbook settings, with _File / Logbook Settings..._ Note that the weekly backups (the period can be changed) will be stored in a relative folder called "Backups".
