### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by sergiomars** [till213/SkyDolly#54]
**Describe the bug**
Hello from Migros

**To Reproduce**
1. Hello
2. From Migros

**Expected behavior**
Gugus, wie gahts?

**Screenshots**
:)

**Application version:**
1.2.3

**Additional context**
Gruess Sergio

**Comment by till213** [comment]
This issue is very much reproducible - we need to discüss this in pörson ;)

**Comment by till213** [comment]
Wie gseht's nöchst Wuche us? Mir händ wölle i'd Ferie, aber wenn's kei Schnee hät...

**Comment by sergiomars** [comment]
Hoi oli
Sorry für di spaht Antwort.
Mir hend die wuche no igwöhnig ide kita. Wie wärs nögscht wuche mal zmittag esse? Mo, mi oder do wür ga.
Lg

**Comment by till213** [comment]
Successfully resolved :)

**Comment by sergiomars** [comment]
Thx for all the investigations. I might open a follow-up for further questions :)
