### ISSUE TITLE
Display decimal lat/long

### ISSUE THREAD

**Issue by scondas** [till213/SkyDolly#89]
**Is your feature request related to a problem? Please describe.**
I deal with decimal lat/long, not hour minutes second.

**Describe the solution you'd like**
Add decimal lat/long to simulation variable display.

**Comment by till213** [comment]
"I deal with decimal lat/long, not hour minutes second."

Most people - including me - write coordinates in DMS notation. While I agree that it would be nice to be able to select the preferred unit (including "Imperial vs metric system" etc.) this is very low on my to-do list (if at all) so I am closing this issue, as this won't be implemented anytime soon (there are more useful features ahead).

If you really want to "deal with lat/lon values" then you can export your flight as e.g. GeoJSON or CSV and do all kind of data analysis - with decimal coordinates ;)

**Comment by scondas** [comment]
While you say "most people" use DMS, I disagree.  Here are examples from the aviation world that use decimal: Flightradar24 Web GUI Display, ADS=B web display (https://globe.adsbexchange.com/?icao=aa9b42&lat=32.646&lon=-102.170&zoom=5.5&showTrace=2023-02-04&leg=3&trackLabels), Flightradar CSV format, LittleNavigator gpx format, KML format.  Another popular option in aviation is Degrees, minutes and decimal minutes.  Anyway, I appreciate your taking the time to have considered this request.

**Comment by till213** [comment]
Okay, I do take back my "most people" and rephrase it as "I am aware that all display units in Sky Dolly are currently hard-coded to some random choice, either heavily influenced by the default units of MSFS itself (knots, feet, ...) or simply as decided by me" ;)

And yes, I totally agree that it would be nice to have user-defined units, be able to quickly switch between imperial and metric units (and at the end of all that would be proper "internationalisation" - but at least the decimal numbers do take your "user locale" into account already).

All I am saying here that there are plenty of other features that I'd like to implement, and that "cosmetic issues" such as "DMS vs feet" are currently outside of my "time budget". Hence I'd rather close this issue for now, to let you know that it is unlikely that this gets implemented by me anytime soon.

On the other hand I keep my liberty to change my mind anytime about this :) But for now it's going to be DMS, as this is also the unit in which coordinates are displayed in MSFS - so at least I am consistent with MSFS.

**Comment by till213** [comment]
> Flightradar CSV format,

Oh, and just for the record: "raw data formats" do not count in my book ;) After all, I could also argue that Sky Dolly stores its value in decimal format in the database (of course) and exports them as decimal in its various export formats. ;)

**Comment by scondas** [comment]
I agree with your comments on raw data format, and withdraw those examples, I stand by the others.  Again, I really appreciate your time to have considered this request, and I will address it in my private version of the software.

**Comment by till213** [comment]
> I will address it in my private version of the software.

That would be in the "Aircraft Widget":

https://github.com/till213/SkyDolly/blob/65074a5b691856ea86cd7960a7d5512d5703f7c5/src/UserInterface/src/Widget/AircraftWidget.cpp#L78

But somehow I have the feeling that you figured that one out already ;)

**Comment by scondas** [comment]
That's fantastic!  Makes it so much easier to compare the Sky Dolly flight to the original inputs.  Thanks!
